mode: chatops
defaultBranch: 'develop'
branchName: 'issue-${issue.number}'
branches:
  - label: '*'
    prefix: feature/
autoCloseIssue: true
commentMessage: 'Branch ${branchName} created for issue : ${issue.title}'
